#!/usr/bin/env bash

#define functions 
hello(){
  local s=$1
  echo "Hello $s !"
}

goodbye() {
  local s=$1
  echo "goodbye $s!"
}

#check requirements
if (($# == 0)); then
  echo 'name required!' >&2
  exit 1
fi 

# iterate betwene the inputs: 
for name in "$@"; do
  case "$name" in 
    d* | b* ) hello "$name";;
    *) goodbye "$name";;
  esac
done
