#!/usr/bin/env bash

declare -a array=(foo bar baz)


echo "${array[0]}"
echo "${array[1]}"
echo "${array[2]}"

echo "${array[-1]}"


idx=2

echo "idx: ${array[$idx]}"


# look whole the items: 
echo "${array[*]}"
# the start is for when you are making a string of the elements of the arrays 
echo "${array[@]}"
# @ is to iterate the arrray such as 
for item in "${array[@]}"; do
  echo "item is $item"
done



# copying array 
#
second_array=( "${array[@]}")
second_array+=(buddy guy joe) #extend the array 
# to get the lenght there is this method: ${#arrray[@]}

